---
- name: My super Puper 
  hosts: staging_servers
  become: yes

  vars:
   message1: Privet
   message2: World
   secret: RTRTRTRTRYTRYTRYTRYTRYTR

  tasks:
  - name: Print secret vars
    debug:
     var: secret

  - debug:
      msg: "Secretnoe slovo {{ secret }}"

  - debug:
      msg: "Vladelec etogo servera -->{{ owner }}<--"

  - set_fact: full_message="{{message1}} {{message2}} from {{owner}}"

  - debug:
      var: full_message

  - debug:
      var: ansible_distribution

  - shell: uptime
    register: results
  
  - debug:
     var: results

  - debug:
     var: results.stdout
