---
 - name: Install Http servers and Upload My Web Pages
   hosts: all
   become: yes

   vars: 
     source_dir: /home/ec2-user/html
     destination_dir: /var/www


   tasks:
    - name: Check and print linux name
      debug: var=ansible_os_family

    - block:  # block for Redhat
     
       - name: Install Apapche web server for RedHat
         yum: name=httpd state=latest

       - name: Copy my Web servers
         copy: src={{ source_dir }} dest={{ destination_dir }}
         notify: Restart apache Redhat

       - name: Start Web servers for Redhat
         service: name=httpd state=started enabled=yes
      
      when: ansible_os_family == "RedHat"

    - block:  # block for Ubuntu


       - name: Install Apache web server for Ubuntu
         apt: name=apache2 state=latest

       - name: Copy my Web servers
         copy: src={{ source_dir }} dest={{ destination_dir }}
         notify: Restart apache Ubuntu

       - name: Start Web servers for ubuntu
         service: name=apache2 state=started enabled=yes

      when: ansible_os_family == "Debian"
   
   handlers:
   - name: Restart apache Redhat
     service: name=httpd state=restarted 

   - name: Restart apache Ubuntu
     service: name=apache2 state=restarted


