---
# handlers file for deploy_apache_web
- name: Restart apache Redhat
  service: name=httpd state=restarted
  when: ansible_os_family == "RedHat"

- name: Restart apache Ubuntu
  service: name=apache2 state=restarted
  when: ansible_os_family == "Debian"


